[versions]
agp = "8.7.1"
kotlin = "1.9.24"
playServicesWearable = "18.2.0"
retrofit = "2.9.0"
workManager = "2.9.0"
gson = "2.10.1"
okhttpLogging = "4.12.0"

[libraries]
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "retrofit" }
work-runtime = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
okhttp-logging = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttpLogging" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

